### ISSUE TITLE
Incorrect handling of long size packet

### ISSUE THREAD

**Issue by Toufinet** [m8rge/cwebsocket#19]
Hi,

I've found you have some mistakes when handling long size packet.
In websocket.c , line 249, you have a mistake of endianness.
I patched it this way :
        //memcpy(&payloadLength16b, &inputFrame[2], *payloadFieldExtraBytes);
        payloadLength16b = (((uint16_t)inputFrame[2]) << 8 ) | inputFrame[3];

For sure you have the same mistake at line 255, but I couldn't test it.

Then you have another mistake in websocket.c , line 296 :
It's not :
if (payloadLength < inputLength-6-payloadFieldExtraBytes)
but :
if (payloadLength > inputLength-6-payloadFieldExtraBytes)

Or mabye it should be >= ...

Best regards,
Vincent.

**Comment by m8rge** [comment]
@Toufinet Are you serious about https://github.com/m8rge/cwebsocket/blob/master/lib/websocket.c#L294 ? This line absolutely right. Please, provide you decisions about possible mistake.

**Comment by Toufinet** [comment]
If I don't patch https://github.com/m8rge/cwebsocket/blob/master/lib/websocket.c#L294 by changing "<" into ">", it still doesn't work with long size packets.

The reason is that on the first frame, payloadLenght equals the data length and not the payload of the first frame.
This function should return "WS_INCOMPLETE_FRAME" when payloadLength is higher than inputLength-6-payloadFieldExtraBytes and not what is currently written.

I have deployed this on hundreds of Windows machines ... works fine :)
