### ISSUE TITLE
base64 encode bug

### ISSUE THREAD

**Issue by leleb** [m8rge/cwebsocket#20]
base64 encoding routine is not working correctly, use this instead:

static size_t base64(char *dst, size_t dst_len, const unsigned char *src, size_t src_len)
{
  static const char *b64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  int i, j, a, b, c;

  if (base64len(src_len) > dst_len) return 0;
  for (i = j = 0; i < src_len; i += 3)
  {
    a = src[i];
    b = i + 1 >= src_len ? 0 : src[i + 1];
    c = i + 2 >= src_len ? 0 : src[i + 2];

```
dst[j++] = b64[a >> 2];
dst[j++] = b64[((a & 3) << 4) | (b >> 4)];
if (i + 1 < src_len) { dst[j++] = b64[(b & 15) << 2 | (c >> 6)]; }
if (i + 2 < src_len) { dst[j++] = b64[c & 63]; }
```

  }
  while (j % 4 != 0) { dst[j++] = '='; }
 dst[j++] = '\0';
 return j;
}

**Comment by m8rge** [comment]
You can post your bug here https://github.com/afterwise/aw-base64
